Importing rustc-1.62.0
Test: ./build.py --lto=thin
Bug: 236723597
Change-Id: I3e25aff564eae13de6385b71ef3b45646a405916

diff --git a/src/tools/rust-analyzer/.github/workflows/ci.yaml b/src/tools/rust-analyzer/.github/workflows/ci.yaml
--- a/src/tools/rust-analyzer/.github/workflows/ci.yaml
+++ b/src/tools/rust-analyzer/.github/workflows/ci.yaml
@@ -1,11 +1,13 @@
+# Please make sure that the `needs` fields for both `end-success` and `end-failure`
+# are updated when adding new jobs!
+
 name: CI
 on:
   pull_request:
   push:
     branches:
-    - master
-    - staging
-    - trying
+    - auto
+    - try
 
 env:
   CARGO_INCREMENTAL: 0
@@ -17,7 +19,7 @@ env:
 
 jobs:
   rust:
-    if: github.repository == 'rust-analyzer/rust-analyzer'
+    if: github.repository == 'rust-lang/rust-analyzer'
     name: Rust
     runs-on: ${{ matrix.os }}
     env:
@@ -30,7 +32,7 @@ jobs:
 
     steps:
     - name: Checkout repository
-      uses: actions/checkout@v2
+      uses: actions/checkout@v3
       with:
         ref: ${{ github.event.pull_request.head.sha }}
         fetch-depth: 20
@@ -62,7 +64,7 @@ jobs:
 
   # Weird targets to catch non-portable code
   rust-cross:
-    if: github.repository == 'rust-analyzer/rust-analyzer'
+    if: github.repository == 'rust-lang/rust-analyzer'
     name: Rust Cross
     runs-on: ubuntu-latest
 
@@ -74,7 +76,7 @@ jobs:
 
     steps:
     - name: Checkout repository
-      uses: actions/checkout@v2
+      uses: actions/checkout@v3
 
     - name: Install Rust toolchain
       uses: actions-rs/toolchain@v1
@@ -99,7 +101,7 @@ jobs:
         done
 
   typescript:
-    if: github.repository == 'rust-analyzer/rust-analyzer'
+    if: github.repository == 'rust-lang/rust-analyzer'
     name: TypeScript
     strategy:
       fail-fast: false
@@ -110,7 +112,7 @@ jobs:
 
     steps:
     - name: Checkout repository
-      uses: actions/checkout@v2
+      uses: actions/checkout@v3
 
     - name: Install Nodejs
       uses: actions/setup-node@v1
@@ -150,3 +152,21 @@ jobs:
 
     - run: npm run package --scripts-prepend-node-path
       working-directory: ./editors/code
+
+  end-success:
+    name: bors build finished
+    if: github.event.pusher.name == 'bors' && success()
+    runs-on: ubuntu-latest
+    needs: [rust, rust-cross, typescript]
+    steps:
+      - name: Mark the job as successful
+        run: exit 0
+
+  end-failure:
+    name: bors build finished
+    if: github.event.pusher.name == 'bors' && (failure() || cancelled())
+    runs-on: ubuntu-latest
+    needs: [rust, rust-cross, typescript]
+    steps:
+      - name: Mark the job as a failure
+        run: exit 1
