Importing rustc-1.64.0
Test: ./build.py --lto=thin
Change-Id: I4bcdffd581b250b7778571402bd05c3003070b62

diff --git a/src/tools/miri/miri b/src/tools/miri/miri
--- a/src/tools/miri/miri
+++ b/src/tools/miri/miri
@@ -5,14 +5,15 @@ USAGE=$(cat <<"EOF"
 
 ./miri install <flags>:
 Installs the miri driver and cargo-miri. <flags> are passed to `cargo
-install`.  Sets up the rpath such that the installed binary should work in any
-working directory.
+install`. Sets up the rpath such that the installed binary should work in any
+working directory. However, the rustup toolchain when invoking `cargo miri`
+needs to be the same one used for `./miri install`.
 
 ./miri build <flags>:
-Just build miri.  <flags> are passed to `cargo build`.
+Just build miri. <flags> are passed to `cargo build`.
 
 ./miri check <flags>:
-Just check miri.  <flags> are passed to `cargo check`.
+Just check miri. <flags> are passed to `cargo check`.
 
 ./miri test <flags>:
 Build miri, set up a sysroot and then run the test suite. <flags> are passed
@@ -20,10 +21,22 @@ to the final `cargo test` invocation.
 
 ./miri run <flags>:
 Build miri, set up a sysroot and then run the driver with the given <flags>.
+(Also respects MIRIFLAGS environment variable.)
 
-All commands also exist in a "-debug" variant (e.g. "./miri run-debug
-<flags>") which uses debug builds instead of release builds, for faster build
-times and slower execution times.
+./miri fmt <flags>:
+Format all sources and tests. <flags> are passed to `rustfmt`.
+
+./miri clippy <flags>:
+Runs clippy on all sources. <flags> are passed to `cargo clippy`.
+
+./miri many-seeds <command>:
+Runs <command> over and over again with different seeds for Miri. The MIRIFLAGS
+variable is set to its original value appended with ` -Zmiri-seed=$SEED` for
+many different seeds.
+
+./miri bench <benches>:
+Runs the benchmarks from bench-cargo-miri in hyperfine. hyperfine needs to be installed.
+<benches> can explicitly list the benchmarks to run; by default, all of them are run.
 
   ENVIRONMENT VARIABLES
 
@@ -35,42 +48,97 @@ Pass extra flags to all cargo invocations.
 EOF
 )
 
-## Preparation
-TARGET=$(rustc --version --verbose | grep "^host:" | cut -d ' ' -f 2)
-SYSROOT=$(rustc --print sysroot)
-LIBDIR=$SYSROOT/lib/rustlib/$TARGET/lib
+## We need to know where we are.
 # macOS does not have a useful readlink/realpath so we have to use Python instead...
-MIRIDIR=$(dirname "$(python3 -c 'import os, sys; print(os.path.realpath(sys.argv[1]))' "$0")")
+MIRIDIR=$(python3 -c 'import os, sys; print(os.path.dirname(os.path.realpath(sys.argv[1])))' "$0")
+
+## Run the auto-things.
+if [ -z "$MIRI_AUTO_OPS" ]; then
+    export MIRI_AUTO_OPS=42
+
+    # Run this first, so that the toolchain doesn't change after
+    # other code has run.
+    if [ -f "$MIRIDIR/.auto-everything" ] || [ -f "$MIRIDIR/.auto-toolchain" ] ; then
+        (cd "$MIRIDIR" && ./rustup-toolchain)
+    fi
+
+    if [ -f "$MIRIDIR/.auto-everything" ] || [ -f "$MIRIDIR/.auto-fmt" ] ; then
+        $0 fmt
+    fi
+
+    if [ -f "$MIRIDIR/.auto-everything" ] || [ -f "$MIRIDIR/.auto-clippy" ] ; then
+        $0 clippy -- -D warnings
+    fi
+fi
+
+## Determine command and toolchain.
+COMMAND="$1"
+[ $# -gt 0 ] && shift
+# Doing this *after* auto-toolchain logic above, since that might change the toolchain.
+TOOLCHAIN=$(cd "$MIRIDIR"; rustup show active-toolchain | head -n 1 | cut -d ' ' -f 1)
+
+## Handle some commands early, since they should *not* alter the environment.
+case "$COMMAND" in
+many-seeds)
+    for SEED in $({ echo obase=16; seq 0 255; } | bc); do
+        echo "Trying seed: $SEED"
+        MIRIFLAGS="$MIRIFLAGS -Zmiri-seed=$SEED" $@ || { echo "Failing seed: $SEED"; break; }
+    done
+    exit 0
+    ;;
+bench)
+    # Make sure we have an up-to-date Miri installed
+    "$0" install
+    # Run the requested benchmarks
+    if [ -z "$@" ]; then
+        BENCHES=( $(ls "$MIRIDIR/bench-cargo-miri" ) )
+    else
+        BENCHES=("$@")
+    fi
+    for BENCH in "${BENCHES[@]}"; do
+        hyperfine -w 1 -m 5 --shell=none "cargo +$TOOLCHAIN miri run --manifest-path bench-cargo-miri/$BENCH/Cargo.toml"
+    done
+    exit 0
+    ;;
+esac
+
+## Prepare the environment
+# Determine some toolchain properties
+TARGET=$(rustc +$TOOLCHAIN --version --verbose | grep "^host:" | cut -d ' ' -f 2)
+SYSROOT=$(rustc +$TOOLCHAIN --print sysroot)
+LIBDIR=$SYSROOT/lib/rustlib/$TARGET/lib
 if ! test -d "$LIBDIR"; then
     echo "Something went wrong determining the library dir."
     echo "I got $LIBDIR but that does not exist."
     echo "Please report a bug at https://github.com/rust-lang/miri/issues."
     exit 2
 fi
-if [ -z "$CARGO_INCREMENTAL" ]; then
-    # Default CARGO_INCREMENTAL to 1.
-    export CARGO_INCREMENTAL=1
-fi
+
+# Prepare flags for cargo and rustc.
+CARGO="cargo +$TOOLCHAIN"
+# Share target dir between `miri` and `cargo-miri`.
 if [ -z "$CARGO_TARGET_DIR" ]; then
-    # Share target dir between `miri` and `cargo-miri`.
     export CARGO_TARGET_DIR="$MIRIDIR/target"
 fi
+# We configure dev builds to not be unusably slow.
+if [ -z "$CARGO_PROFILE_DEV_OPT_LEVEL" ]; then
+    export CARGO_PROFILE_DEV_OPT_LEVEL=2
+fi
 # We set the rpath so that Miri finds the private rustc libraries it needs.
-# We enable debug-assertions to get tracing.
-# We enable line-only debuginfo for backtraces.
-export RUSTFLAGS="-C link-args=-Wl,-rpath,$LIBDIR -C debug-assertions -C debuginfo=1 $RUSTFLAGS"
+export RUSTFLAGS="-C link-args=-Wl,-rpath,$LIBDIR $RUSTFLAGS"
 
 ## Helper functions
 
-# Build a sysroot and set MIRI_SYSROOT to use it.  Arguments are passed to `cargo miri setup`.
+# Build a sysroot and set MIRI_SYSROOT to use it. Arguments are passed to `cargo miri setup`.
 build_sysroot() {
-    # Build once, for the user to see.
-    cargo run $CARGO_BUILD_FLAGS --manifest-path "$MIRIDIR"/cargo-miri/Cargo.toml -- miri setup "$@"
-    # Call again, to just set env var.
-    export MIRI_SYSROOT="$(cargo run $CARGO_BUILD_FLAGS --manifest-path "$MIRIDIR"/cargo-miri/Cargo.toml -q -- miri setup --print-sysroot "$@")"
+    if ! MIRI_SYSROOT="$($CARGO run $CARGO_EXTRA_FLAGS --manifest-path "$MIRIDIR"/cargo-miri/Cargo.toml -q -- miri setup --print-sysroot "$@")"; then
+        echo "'cargo miri setup' failed"
+        exit 1
+    fi
+    export MIRI_SYSROOT
 }
 
-# Prepare and set MIRI_SYSROOT.  Respects `MIRI_TEST_TARGET` and takes into account
+# Prepare and set MIRI_SYSROOT. Respects `MIRI_TEST_TARGET` and takes into account
 # locally built vs. distributed rustc.
 find_sysroot() {
     if [ -n "$MIRI_SYSROOT" ]; then
@@ -87,74 +155,66 @@ find_sysroot() {
 
 ## Main
 
-# Determine command.
-COMMAND="$1"
-[ $# -gt 0 ] && shift
-
-# Determine flags passed to all cargo invocations.
-# This is a bit more annoying that one would hope due to
-# <https://github.com/rust-lang/cargo/issues/6992>.
-case "$COMMAND" in
-*-debug)
-    CARGO_INSTALL_FLAGS="--target $TARGET --debug $CARGO_EXTRA_FLAGS"
-    CARGO_BUILD_FLAGS="--target $TARGET $CARGO_EXTRA_FLAGS"
-    ;;
-*)
-    CARGO_INSTALL_FLAGS="--target $TARGET $CARGO_EXTRA_FLAGS"
-    CARGO_BUILD_FLAGS="--target $TARGET --release $CARGO_EXTRA_FLAGS"
-    ;;
-esac
-
 # Run command.
 case "$COMMAND" in
-install|install-debug)
-    # "--locked" to respect the Cargo.lock file if it exists,
-    # "--offline" to avoid querying the registry (for yanked packages).
-    cargo install $CARGO_INSTALL_FLAGS --path "$MIRIDIR" --force --locked --offline "$@"
-    cargo install $CARGO_INSTALL_FLAGS --path "$MIRIDIR"/cargo-miri --force --locked --offline "$@"
+install)
+    # "--locked" to respect the Cargo.lock file if it exists.
+    $CARGO install $CARGO_EXTRA_FLAGS --path "$MIRIDIR" --force --locked "$@"
+    $CARGO install $CARGO_EXTRA_FLAGS --path "$MIRIDIR"/cargo-miri --force --locked "$@"
     ;;
-check|check-debug)
+check)
     # Check, and let caller control flags.
-    cargo check $CARGO_BUILD_FLAGS --manifest-path "$MIRIDIR"/Cargo.toml --all-targets "$@"
-    cargo check $CARGO_BUILD_FLAGS --manifest-path "$MIRIDIR"/cargo-miri/Cargo.toml "$@"
+    $CARGO check $CARGO_EXTRA_FLAGS --manifest-path "$MIRIDIR"/Cargo.toml --all-targets "$@"
+    $CARGO check $CARGO_EXTRA_FLAGS --manifest-path "$MIRIDIR"/cargo-miri/Cargo.toml "$@"
     ;;
-build|build-debug)
+build)
     # Build, and let caller control flags.
-    cargo build $CARGO_BUILD_FLAGS --manifest-path "$MIRIDIR"/Cargo.toml "$@"
-    cargo build $CARGO_BUILD_FLAGS --manifest-path "$MIRIDIR"/cargo-miri/Cargo.toml "$@"
+    $CARGO build $CARGO_EXTRA_FLAGS --manifest-path "$MIRIDIR"/Cargo.toml "$@"
+    $CARGO build $CARGO_EXTRA_FLAGS --manifest-path "$MIRIDIR"/cargo-miri/Cargo.toml "$@"
     ;;
-test|test-debug|bless|bless-debug)
+test|bless)
     # First build and get a sysroot.
-    cargo build $CARGO_BUILD_FLAGS
+    $CARGO build $CARGO_EXTRA_FLAGS --manifest-path "$MIRIDIR"/Cargo.toml
     find_sysroot
-    case "$COMMAND" in
-    bless|bless-debug)
+    if [ "$COMMAND" = "bless" ]; then
         export MIRI_BLESS="Gesundheit"
-        ;;
-    esac
+    fi
     # Then test, and let caller control flags.
     # Only in root project and ui_test as `cargo-miri` has no tests.
-    cargo test $CARGO_BUILD_FLAGS "$@"
-    cargo test $CARGO_BUILD_FLAGS --manifest-path ui_test/Cargo.toml "$@"
+    $CARGO test $CARGO_EXTRA_FLAGS --manifest-path "$MIRIDIR"/Cargo.toml "$@"
+    $CARGO test $CARGO_EXTRA_FLAGS --manifest-path "$MIRIDIR"/ui_test/Cargo.toml "$@"
     ;;
-run|run-debug)
-    # Scan for "--target" to set the "MIRI_TEST_TARGET" env var so
+run)
+    # Scan for "--target" to overwrite the "MIRI_TEST_TARGET" env var so
     # that we set the MIRI_SYSROOT up the right way.
-    if [ -z "$MIRI_TEST_TARGET" ]; then
-        for ARG in "$@"; do
-            if [ "$LAST_ARG" = "--target" ]; then
-                # Found it!
-                export MIRI_TEST_TARGET="$ARG"
-                break
-            fi
-            LAST_ARG="$ARG"
-        done
+    FOUND_TARGET_OPT=0
+    for ARG in "$@"; do
+        if [ "$LAST_ARG" = "--target" ]; then
+            # Found it!
+            export MIRI_TEST_TARGET="$ARG"
+            FOUND_TARGET_OPT=1
+            break
+        fi
+        LAST_ARG="$ARG"
+    done
+    if [ "$FOUND_TARGET_OPT" = "0" ] && [ -n "$MIRI_TEST_TARGET" ]; then
+        # Make sure Miri actually uses this target.
+        MIRIFLAGS="$MIRIFLAGS --target $MIRI_TEST_TARGET"
     fi
     # First build and get a sysroot.
-    cargo build $CARGO_BUILD_FLAGS
+    $CARGO build $CARGO_EXTRA_FLAGS --manifest-path "$MIRIDIR"/Cargo.toml
     find_sysroot
     # Then run the actual command.
-    exec cargo run $CARGO_BUILD_FLAGS -- --sysroot "$MIRI_SYSROOT" "$@"
+    exec $CARGO run $CARGO_EXTRA_FLAGS --manifest-path "$MIRIDIR"/Cargo.toml -- $MIRIFLAGS "$@"
+    ;;
+fmt)
+    find "$MIRIDIR" -not \( -name target -prune \) -name '*.rs' \
+        | xargs rustfmt +$TOOLCHAIN --edition=2021 --config-path "$MIRIDIR/rustfmt.toml" "$@"
+    ;;
+clippy)
+    $CARGO clippy $CARGO_EXTRA_FLAGS --manifest-path "$MIRIDIR"/Cargo.toml --all-targets "$@"
+    $CARGO clippy $CARGO_EXTRA_FLAGS --manifest-path "$MIRIDIR"/ui_test/Cargo.toml --all-targets "$@"
+    $CARGO clippy $CARGO_EXTRA_FLAGS --manifest-path "$MIRIDIR"/cargo-miri/Cargo.toml "$@"
     ;;
 *)
     if [ -n "$COMMAND" ]; then
